version: 2.1

jobs:
  crashtest:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run:
          command: sh start_crashtest_circleci.sh $CRASHTEST_WEBHOOK
      - store_test_results:
          path: ~/crashtest

workflows:
  workflow:
    jobs:
      - crashtest