version: 2.1

jobs:
  crashtest:
    docker:
      - image: alpine:latest
    steps:
      - run:
          command: sh './start_crashtest.sh $CRASHTEST_WEBHOOK'
      - store_test_results:
          path: ~/crashtest

workflows:
  workflow:
    jobs:
      - crashtest