on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Run Crashtest Security Scan
    steps:
    - name: Crashtest Security Action Step
      id: crashtest-security
      uses: phylu/crashtest-security-action@v0.1.15
      with:
        crashtest-webhook: '${{ secrets.CRASHTEST_WEBHOOK }}'
        pull-report: 'true'